import "./globals.css";

import Footer from "@/components/Shared-components/Footer";
import Header from "@/components/Shared-components/Header";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./../themes/theme";
import CssBaseline from "@mui/material/CssBaseline";
import { work_Sans } from "@/fonts";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={work_Sans.className}>
        <ReactQueryProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Header />
            {children}
            <Footer />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
